version: '3'

services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.8
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    env_file:
      - ./env/rabbitmq.env
    networks:
      - modern_network
    volumes:
      - 'rabbitmq_data:/bitnami'
      - ./ops/rabbitmq.json:/etc/rabbitmq/definitions.json
      - ./ops/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  database:
    image: 'postgres'
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./env/database.env
    networks:
      - modern_network
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./ops/init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  api:
    depends_on:
      - rabbitmq
    build: ./api
    ports:
      - "3333:3333"
    env_file:
      - ./env/api.env
    networks:
      - modern_network
  consumer:
    depends_on:
      - api
      - database
    build: ./consumer
    env_file:
      - ./env/consumer.env
    networks:
      - modern_network
volumes:
  rabbitmq_data:
    driver: local
  database-data:
networks:
  modern_network:
    driver: bridge