version: '2'

services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.8
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_VHOST=vhost
    volumes:
      - 'rabbitmq_data:/bitnami'
    networks:
      - modern_network
  api:
    build: ./api
    ports:
      - "3333:3333"
    environment:
      - RABBITMQ_USER=test
      - RABBITMQ_PWD=test
      - MESSAGE_BROKER_URL=amqp://modern_api_rabbitmq_1
    networks:
      - modern_network
volumes:
  rabbitmq_data:
    driver: local
networks:
  modern_network:
    driver: bridge